### PR TITLE
Update mi600-webif.php

### PR DESCRIPTION
**Pull request by soe135**
Some changes for stability improvement and correct operation with more than one MI-600 inverters in the same grid.

### CODE REVIEW

**Comment by dr-ni** [comment]
Well done, is this also fixing the drift between our local counter and the Inverter?

**Comment by soe135** [comment]
Could you please use the code I published today for the pull-request!? Because the code from yesterday had a small issue regarding the use of the variable $_SERVER['DOCUMENT_ROOT']; The code for the second pull request solved this small issue and works now without any problems also on other web-servers.

**Comment by dr-ni** [comment]
there was a conflict is it ok now like this?

**Comment by soe135** [comment]
As I could monitor till today there is no real drift between the inverter and the value calculated in 123solar. Only few decimal places behind the full KWH value. In my opinion this is the result of the shortage of decimal places by the inverter webif.

**Comment by soe135** [comment]
In my opinion it looks good now. Do you create a pull request to jeanmarc77 for the change!?

**Comment by dr-ni** [comment]
how long are you running it?
I've noticed around +1kWh per month

**Comment by soe135** [comment]
At this time I use it for two weeks. I will have an eye on the drift in the following weeks. Maybe I can find a better idea/solution in the future to reduce a possible drift.

**Comment by dr-ni** [comment]
https://github.com/jeanmarc77/123solar/pull/25

**Comment by dr-ni** [comment]
can we include this without conflict?

https://github.com/jeanmarc77/123solar/pull/26

**Comment by soe135** [comment]
@dr-ni: Please have a look on my last changes in the file mi600-webif.php in the 123solar repository of jeanmarc77. I've done some changes regarding the positive drift we talked about. Now it works for me without any problems and the KWHT-value in 123solar is really close to the value stored in the inverter.
Please keep also in mind that the location of the file 'lastKWHtotal.dat' has moved in this patch based on the proposal of jeanmarc77. Regarding this I have inserted a comment at the top of file mi600-webif.php.

**Comment by dr-ni** [comment]
very nice, well done :-)

**Pull request merged**
